### ISSUE TITLE
为什么readme里面R50的pth，我拉下来NDS复现不出来

### ISSUE THREAD

**Issue by FlyingSong888** [LiewFeng/RayDN#10]
`mAP: 0.4713
mATE: 0.5834
mASE: 0.7039
mAOE: 1.5492
mAVE: 0.2547
mAAE: 0.1973
NDS: 0.4617
Eval time: 156.5s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.648   0.410   0.748   1.585   0.223   0.196
truck   0.438   0.634   0.789   1.586   0.189   0.187
bus     0.437   0.713   0.854   1.566   0.524   0.294
trailer 0.239   0.948   0.838   1.548   0.176   0.163
construction_vehicle    0.156   0.899   0.679   1.558   0.114   0.369
pedestrian      0.541   0.570   0.331   1.580   0.305   0.145
motorcycle      0.489   0.528   0.792   1.576   0.344   0.217
bicycle 0.425   0.478   0.810   1.668   0.163   0.008
traffic_cone    0.682   0.322   0.312   nan     nan     nan
barrier 0.658   0.332   0.887   1.277   nan     nan
{'pts_bbox_NuScenes/car_AP_dist_0.5': 0.3303, 'pts_bbox_NuScenes/car_AP_dist_1.0': 0.6092, 'pts_bbox_NuScenes/car_AP_dist_2.0': 0.7889, 'pts_bbox_NuScenes/car_AP_dist_4.0': 0.8644, 
'pts_bbox_NuScenes/car_trans_err': 0.4096, 'pts_bbox_NuScenes/car_scale_err': 0.748, 'pts_bbox_NuScenes/car_orient_err': 1.5849, 'pts_bbox_NuScenes/car_vel_err': 0.223, 'pts_bbox_Nu
Scenes/car_attr_err': 0.1962, 'pts_bbox_NuScenes/mATE': 0.5834, 'pts_bbox_NuScenes/mASE': 0.7039, 'pts_bbox_NuScenes/mAOE': 1.5492, 'pts_bbox_NuScenes/mAVE': 0.2547, 'pts_bbox_NuSce
nes/mAAE': 0.1973, 'pts_bbox_NuScenes/truck_AP_dist_0.5': 0.1171, 'pts_bbox_NuScenes/truck_AP_dist_1.0': 0.325, 'pts_bbox_NuScenes/truck_AP_dist_2.0': 0.5981, 'pts_bbox_NuScenes/tru
ck_AP_dist_4.0': 0.7114, 'pts_bbox_NuScenes/truck_trans_err': 0.6342, 'pts_bbox_NuScenes/truck_scale_err': 0.7885, 'pts_bbox_NuScenes/truck_orient_err': 1.5857, 'pts_bbox_NuScenes/t
ruck_vel_err': 0.1891, 'pts_bbox_NuScenes/truck_attr_err': 0.187, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_0.5': 0.0, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_1.0': 0.
0551, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_2.0': 0.2317, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_4.0': 0.3356, 'pts_bbox_NuScenes/construction_vehicle_trans_err':
 0.8992, 'pts_bbox_NuScenes/construction_vehicle_scale_err': 0.6788, 'pts_bbox_NuScenes/construction_vehicle_orient_err': 1.558, 'pts_bbox_NuScenes/construction_vehicle_vel_err': 0.
1143, 'pts_bbox_NuScenes/construction_vehicle_attr_err': 0.3689, 'pts_bbox_NuScenes/bus_AP_dist_0.5': 0.0641, 'pts_bbox_NuScenes/bus_AP_dist_1.0': 0.2849, 'pts_bbox_NuScenes/bus_AP_
dist_2.0': 0.6222, 'pts_bbox_NuScenes/bus_AP_dist_4.0': 0.7763, 'pts_bbox_NuScenes/bus_trans_err': 0.7135, 'pts_bbox_NuScenes/bus_scale_err': 0.8542, 'pts_bbox_NuScenes/bus_orient_e
rr': 1.5658, 'pts_bbox_NuScenes/bus_vel_err': 0.5238, 'pts_bbox_NuScenes/bus_attr_err': 0.2942, 'pts_bbox_NuScenes/trailer_AP_dist_0.5': 0.0009, 'pts_bbox_NuScenes/trailer_AP_dist_1
.0': 0.0832, 'pts_bbox_NuScenes/trailer_AP_dist_2.0': 0.3189, 'pts_bbox_NuScenes/trailer_AP_dist_4.0': 0.5518, 'pts_bbox_NuScenes/trailer_trans_err': 0.948, 'pts_bbox_NuScenes/trail
er_scale_err': 0.8378, 'pts_bbox_NuScenes/trailer_orient_err': 1.5475, 'pts_bbox_NuScenes/trailer_vel_err': 0.1765, 'pts_bbox_NuScenes/trailer_attr_err': 0.1629, 'pts_bbox_NuScenes/
barrier_AP_dist_0.5': 0.4216, 'pts_bbox_NuScenes/barrier_AP_dist_1.0': 0.6483, 'pts_bbox_NuScenes/barrier_AP_dist_2.0': 0.7604, 'pts_bbox_NuScenes/barrier_AP_dist_4.0': 0.8034, 'pts
_bbox_NuScenes/barrier_trans_err': 0.3316, 'pts_bbox_NuScenes/barrier_scale_err': 0.887, 'pts_bbox_NuScenes/barrier_orient_err': 1.2767, 'pts_bbox_NuScenes/barrier_vel_err': nan, 'p
ts_bbox_NuScenes/barrier_attr_err': nan, 'pts_bbox_NuScenes/motorcycle_AP_dist_0.5': 0.1979, 'pts_bbox_NuScenes/motorcycle_AP_dist_1.0': 0.4171, 'pts_bbox_NuScenes/motorcycle_AP_dis
t_2.0': 0.6273, 'pts_bbox_NuScenes/motorcycle_AP_dist_4.0': 0.7154, 'pts_bbox_NuScenes/motorcycle_trans_err': 0.5275, 'pts_bbox_NuScenes/motorcycle_scale_err': 0.7925, 'pts_bbox_NuS
cenes/motorcycle_orient_err': 1.5756, 'pts_bbox_NuScenes/motorcycle_vel_err': 0.3439, 'pts_bbox_NuScenes/motorcycle_attr_err': 0.2168, 'pts_bbox_NuScenes/bicycle_AP_dist_0.5': 0.211
8, 'pts_bbox_NuScenes/bicycle_AP_dist_1.0': 0.3742, 'pts_bbox_NuScenes/bicycle_AP_dist_2.0': 0.5281, 'pts_bbox_NuScenes/bicycle_AP_dist_4.0': 0.5855, 'pts_bbox_NuScenes/bicycle_tran
s_err': 0.4782, 'pts_bbox_NuScenes/bicycle_scale_err': 0.8095, 'pts_bbox_NuScenes/bicycle_orient_err': 1.6681, 'pts_bbox_NuScenes/bicycle_vel_err': 0.1628, 'pts_bbox_NuScenes/bicycl
e_attr_err': 0.0076, 'pts_bbox_NuScenes/pedestrian_AP_dist_0.5': 0.1899, 'pts_bbox_NuScenes/pedestrian_AP_dist_1.0': 0.4713, 'pts_bbox_NuScenes/pedestrian_AP_dist_2.0': 0.6982, 'pts
_bbox_NuScenes/pedestrian_AP_dist_4.0': 0.8049, 'pts_bbox_NuScenes/pedestrian_trans_err': 0.5698, 'pts_bbox_NuScenes/pedestrian_scale_err': 0.3311, 'pts_bbox_NuScenes/pedestrian_ori
ent_err': 1.5803, 'pts_bbox_NuScenes/pedestrian_vel_err': 0.3047, 'pts_bbox_NuScenes/pedestrian_attr_err': 0.1451, 'pts_bbox_NuScenes/traffic_cone_AP_dist_0.5': 0.475, 'pts_bbox_NuS
cenes/traffic_cone_AP_dist_1.0': 0.6497, 'pts_bbox_NuScenes/traffic_cone_AP_dist_2.0': 0.7803, 'pts_bbox_NuScenes/traffic_cone_AP_dist_4.0': 0.8225, 'pts_bbox_NuScenes/traffic_cone_
trans_err': 0.3222, 'pts_bbox_NuScenes/traffic_cone_scale_err': 0.3117, 'pts_bbox_NuScenes/traffic_cone_orient_err': nan, 'pts_bbox_NuScenes/traffic_cone_vel_err': nan, 'pts_bbox_Nu
Scenes/traffic_cone_attr_err': nan, 'pts_bbox_NuScenes/NDS': 0.46171403001604105, 'pts_bbox_NuScenes/mAP': 0.47130308501381357}`

**Comment by LiewFeng** [comment]
mAP是对的，NDS不对的话，可能是pkl的问题，你可能用了你原来的pkl，需要用StreamPETR中的pkl，或者mmdet3d的版本不对
