### ISSUE TITLE
关于网络输入

### ISSUE THREAD

**Issue by DFLyan** [LiewFeng/RayDN#11]
你好，我想问下，现在释放出的代码的config中raydn_r50_704_bs2_seq_428q_nui_60e.py，这个的输入是单帧的还是多帧的？

**Comment by LiewFeng** [comment]
我们的setting跟StreamPETR是一样的，多帧的哈

**Comment by LiewFeng** [comment]
如果你想试一下单帧，可以参考这几个issue，[link 1](https://github.com/exiawsh/StreamPETR/issues/111)，[link 2](https://github.com/exiawsh/StreamPETR/issues/217)，[link 3](https://github.com/exiawsh/StreamPETR/issues/24)
