### ISSUE TITLE
Inquiry on real time camera inference

### ISSUE THREAD

**Issue by Darkthor15** [LiewFeng/RayDN#12]
Hey! Great work and congratulations on your work being accepted by ECCV 2024!
I actually wanted to use this to run inference on my camera feed for object detection can you please guide me through all the changes or what else i need to do in order to run it?

**Comment by LiewFeng** [comment]
Hi, thank you for your interest in our work. RayDN takes several frames of muliti-view(i.e., 6-view) images as input. Besides, it also requires the transformation matirx of the camera. You may follow [StreamPETR](https://github.com/exiawsh/StreamPETR/blob/main/docs/data_preparation.md) and [nuScenes](https://www.nuscenes.org/nuscenes#data-format) to prepare your data.

**Comment by Darkthor15** [comment]
Hi Thank you for your reply and time! 
Do i need to always convert a dataset to nuscenes format? does it support any other? Also how can i just test it on 1 or 2 images?

**Comment by LiewFeng** [comment]
I haven't tried it. You may refer to [link](https://github.com/exiawsh/StreamPETR/issues/217).

**Comment by Darkthor15** [comment]
Thanks a lot! I will refer to it and let you know if i have something else!

**Comment by seawei1993** [comment]
hi , Have you successfully implemented real time inference?
If possible, can you share it?

**Comment by LiewFeng** [comment]
Maybe you can also refer to [link](https://github.com/exiawsh/StreamPETR/issues/16).
