### ISSUE TITLE
How to Use the NuImg dataset to train Resnet50

### ISSUE THREAD

**Issue by wansdd** [LiewFeng/RayDN#13]
Thank you for your great Work, I am confused about train the resnet50 use  the NuImg dataset, is the NuImg dataset a classfication dataset ? would you like to  share the  method simplefiy？Thank you again!

**Comment by LiewFeng** [comment]
Hi, thank you for your interest in our work. We didn't train resnet50 on NuImg. We follow [StreamPETR](https://github.com/exiawsh/StreamPETR) to use the chcakpoints pretrained on NuImg. The NuImg can be found [here](https://www.nuscenes.org/nuimages).
