### ISSUE TITLE
What does the weight file eva02_l_coco_det_sys_o365_remapping.pth refer to

### ISSUE THREAD

**Issue by caojiaxi0505** [LiewFeng/RayDN#17]
I can't find eva02_l_coco_det_sys_o365_remapping.pth

**Comment by LiewFeng** [comment]
You can find it in [StreamPETR](https://github.com/exiawsh/StreamPETR), or download it from [link](https://github.com/exiawsh/storage/releases/download/v1.0/eva02_L_coco_det_sys_o365_remapped.pth).
