### ISSUE TITLE
Config for Argoverse2 validation

### ISSUE THREAD

**Issue by shubhendu-ranadive** [LiewFeng/RayDN#5]
Hello,

Thank you for your excellent work. 
I was looking through your paper and saw that you also performed validation on Argoverse2 dataset.
I was wondering if you have any plans on releasing the config file (also checkpoint if possible) for Argoverse2 dataset?

**Comment by LiewFeng** [comment]
Hi，@shubhendu-ranadive, you may refer to [Far3D](https://github.com/megvii-research/Far3D) for the time being.

**Comment by shubhendu-ranadive** [comment]
> Hi，@shubhendu-ranadive, you may refer to [Far3D](https://github.com/megvii-research/Far3D) for the time being.

Thank you for your reply.
I will check out the Far3D repository for implementation on Argoverse2.
