### ISSUE TITLE
Attempt to apply ray denoising to dense query-based algorithms.

### ISSUE THREAD

**Issue by commc** [LiewFeng/RayDN#6]
Congratulations on the excellent work being accepted by ECCV 2024！
Dense query-based algorithms, such as BEV Former, are also quite popular methods but face the issue of duplicate predictions. I would like to know if ray denoising can be applied to work with dense BEV features?

**Comment by LiewFeng** [comment]
@commc, Thank you for your interest in our work. It should work with BEVFormer, since we only add some queries distributed along the camera ray during training.

**Comment by commc** [comment]
Apologies, I might not have made myself clear. Ray denoising performs excellently in DETR-style multi-view 3D object detectors, and I am wondering if the idea of ray denoising can be applied to non-DETR-style multi-view 3D object detectors? For instance, YOLO detector which generates prediction boxes in each grid of the dense BEV feature.

**Comment by LiewFeng** [comment]
It may not be applicable to non-DETR-style methods. The self attention in the DETR decoder builds the relationship between the quires, which faciliates the suppression of duplicated detections with proper supervision. It seems that YOLO doesn't have self attention layers to enable it.

**Comment by commc** [comment]
Thank you for your response!
