### ISSUE TITLE
权重文件

### ISSUE THREAD

**Issue by suyu-star** [LiewFeng/RayDN#7]
您好，请问这个权重文件具体应该在哪里下载呢，感觉streampetr没有，cascade_mask_rcnn_r50_fpn_coco-20e_20e_nuim-remapped.pth

**Comment by LiewFeng** [comment]
streampetr里有哈，在[这里](https://github.com/exiawsh/StreamPETR/blob/main/docs/data_preparation.md#pretrained-weights)

**Comment by suyu-star** [comment]
> streampetr里有哈，在[这里](https://github.com/exiawsh/StreamPETR/blob/main/docs/data_preparation.md#pretrained-weights)

![屏幕截图 2024-07-26 093425](https://github.com/user-attachments/assets/f9c6f960-17f2-4e05-92ad-c034b8e93e58)
您好，我只看到了这个链接，它对应的不是config文件中的cascade_mask_rcnn_r50_fpn_coco-20e_20e_nuim_20201009_124951-40963960.pth权重文件吗，remapped两者是一致的吗

**Comment by LiewFeng** [comment]
是一样的

**Comment by suyu-star** [comment]
> 是一样的
好的，谢谢
