### ISSUE TITLE
EVAViT代码

### ISSUE THREAD

**Issue by 203402** [LiewFeng/RayDN#9]
您好，backbone里面没有EVAViT的代码，请问这个代码应该去哪里找

**Comment by LiewFeng** [comment]
你好，evavit的代码已更新到backbone下了

**Comment by 203402** [comment]
mAP: 0.2766                                                                     
mATE: 0.7195
mASE: 0.2908
mAOE: 0.7011
mAVE: 0.3550
mAAE: 0.2137
NDS: 0.4103
Eval time: 204.6s

Per-class results:
Object Class        	AP    	ATE   	ASE   	AOE   	AVE   	AAE   
car                 	0.515 	0.498 	0.157 	0.195 	0.307 	0.215 
truck               	0.218 	0.740 	0.230 	0.309 	0.305 	0.184 
bus                 	0.188 	0.916 	0.243 	0.245 	0.794 	0.280 
trailer             	0.031 	1.082 	0.265 	0.849 	0.223 	0.052 
construction_vehicle	0.056 	1.047 	0.543 	1.311 	0.140 	0.424 
pedestrian          	0.326 	0.764 	0.291 	0.785 	0.463 	0.254 
motorcycle          	0.256 	0.646 	0.288 	1.104 	0.440 	0.296 
bicycle             	0.189 	0.523 	0.287 	1.243 	0.168 	0.004 
traffic_cone        	0.520 	0.458 	0.329 	nan   	nan   	nan   
barrier             	0.467 	0.522 	0.274 	0.268 	nan   	nan

您好，这是我用您给的EVAViT作backbone的config在4张3090上跑出来的结果，不知道是哪里出了问题，您有什么建议吗？

**Comment by 203402** [comment]
预训练模型用的是这里的https://huggingface.co/Yuxin-CV/EVA-02/blob/main/eva02/det/eva02_L_coco_det_sys_o365.pth

**Comment by LiewFeng** [comment]
我们是用8卡训练的，4卡训练的话需要调整学习率哈，可以参考这个[链接](https://github.com/exiawsh/StreamPETR/blob/main/docs/training_inference.md#training-recipes)，以及可以check一下权重有没有正确加载
